# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: win32
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 0
    container: registry.videolan.org/vlc-debian-llvm-mingw:20190621125349

    steps:
    - script: git clone https://github.com/videolan/vlc && cd vlc && ./extras/package/win32/build.sh -d