trigger:
- master

jobs:
  - job: win64_llvm
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 0
    container: registry.videolan.org/vlc-debian-llvm-mingw:20190621125349

    steps:
    - script: git clone https://github.com/videolan/vlc/ && cd vlc && ./extras/package/win32/build.sh -d